# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d53eda623e82545c3252d7fbe2279c68d3384f304a7b4f5ae99247d47ede2545a8e3d9ea1aa1ba384568ed7ad8a5c1f0f5cbea4b5a68eaef657d55c3af1c35

test:
  secret_key_base: 116c229791be9eac5a6c4ccdc2e46f4cdf88e2633ce44fd39bc7c84b8e585940e84a994e10608ba10ffb3cd680420724edb9698d265b58d53849c3dd28f0dc60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
